import fs from 'node:fs';
const root = 'dist/client/';
const h = fs.readFileSync(root + 'foam-pump-manufacturer-landingpage/index.html', 'utf8');
console.log('LP bytes:', h.length);
const h1 = (h.match(/<h1[^>]*>[\s\S]*?<\/h1>/i) || [''])[0];
console.log('H1:', h1.replace(/\s+/g, ' ').slice(0, 200));
console.log('has .lp-wrap:', h.includes('class="lp-wrap"'));
console.log('has lp-toggle script:', h.includes('lpToggleFaq'));
console.log('has site header:', h.includes('GET A QUOTE'));
console.log('lp-nav present:', h.includes('lp-nav'));
console.log('lead form action?', /data-lead-form/.test(h));
const form = (h.match(/<form[\s\S]{0,900}?<\/form>/) || [''])[0];
console.log('--- first form ---');
console.log(form.replace(/\s+/g, ' ').slice(0, 700));
console.log('--- leftover wpcf7 markup outside style ---');
const bodyOnly = h.replace(/<style[\s\S]*?<\/style>/gi, '');
console.log('wpcf7 in body:', (bodyOnly.match(/wpcf7/gi) || []).length);
console.log('--- sitemap ---');
const sm = fs.readFileSync(root + 'sitemap-0.xml', 'utf8');
const urls = [...sm.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
console.log('sitemap urls:', urls.length);
console.log('thank-you present:', urls.some((u) => u.includes('thank-you')));
console.log('404 present:', urls.some((u) => u.includes('404')));
console.log('sample:', urls.slice(0, 5).join('\n  '));
