import { defineCollection } from 'astro:content';
import { z } from 'zod/v4';
import { glob } from 'astro/loaders';

/**
 * Content is generated by `npm run sync` from the WordPress REST API.
 * These collections are the typed contract between WP and the rebuild.
 */

const posts = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/posts' }),
  schema: z.object({
    id: z.number(),
    slug: z.string(),
    title: z.string(),
    excerpt: z.string().default(''),
    date: z.string(),
    modified: z.string().optional(),
    categories: z.array(z.string()).default([]),
    categoryNames: z.array(z.string()).default([]),
    heroImage: z.string().default(''),
  }),
});

const products = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/products' }),
  schema: z.object({
    id: z.number(),
    slug: z.string(),
    title: z.string(),
    excerpt: z.string().default(''),
    modified: z.string().optional(),
    categories: z.array(z.string()).default([]),
    categoryNames: z.array(z.string()).default([]),
    image: z.string().default(''),
    imageAlt: z.string().default(''),
    gallery: z.array(z.string()).default([]),
    video: z.string().default(''),

    // ACF technical fields — the B2B spec sheet
    origin: z.string().default(''),
    brand: z.string().default(''),
    customOrder: z.string().default(''),
    oemOdm: z.string().default(''),
    modelNumber: z.string().default(''),
    moq: z.string().default(''),
    price: z.string().default(''),
    packaging: z.string().default(''),
    deliveryTime: z.string().default(''),
    sample: z.string().default(''),
    paymentTerms: z.string().default(''),
    supplyAbility: z.string().default(''),
    material: z.string().default(''),
    plasticType: z.string().default(''),
    types: z.string().default(''),
    usage: z.string().default(''),
    use: z.array(z.string()).default([]),
    characteristic: z.string().default(''),
    size: z.array(z.string()).default([]),
    closure: z.array(z.string()).default([]),
    color: z.string().default(''),
    tubeLength: z.string().default(''),
    packing: z.string().default(''),
    leadTime: z.string().default(''),
  }),
});

export const collections = { posts, products };
